# Generated by Django 5.1.6 on 2025-02-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidding", "0003_auction_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="locked_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
