# Generated by Django 5.1.6 on 2025-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidding", "0004_wallet_locked_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
    ]
