# Generated by Django 5.1.6 on 2025-02-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidding", "0005_auction_is_canceled"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="receipt_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
