# Generated by Django 5.1.6 on 2025-03-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bidding", "0007_wallettransaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WalletTransaction",
        ),
    ]
